apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dimitris/cs548/CS548/Assignment_2/site"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi


---
apiVersion: batch/v1
kind: Job
metadata:
  name: website-548-nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        command: ["/bin/sh", "-c", "./etc/build-site.sh && cp hy548/html/public/index.html /website && ls /website"]
        volumeMounts:
        - name: script
          mountPath: "/etc/build-site.sh"
          subPath: build-site.sh
        - name: website-volume
          mountPath: /website
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: website-config
          defaultMode: 0500
      - name: website-volume
        persistentVolumeClaim:
           claimName: site-volume-claim
         
---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx
spec:
  containers:
      - name: website-server
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: "/usr/share/nginx/html" 
  volumes:
  - name: website-volume
    persistentVolumeClaim:
        claimName: site-volume-claim